# -*- coding: utf-8 -*-
"""CS535_Project_Topic1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c9TZFH-DB-w_iSxlfOlcU27_ZZJ0yYtp

# Topic 1

## Problem 1: What is the problem that the paper aims to solve, and why is this problem important or interesting? Answer this question in two sentences. (5 points)

The problem that this paper aims to solve is the measurement of uncertainity through the usage of distance awareness in deep neural networks. This problem is important since with the estimation on the distance between a test example and the network trained on previous testing example, it is able to give us a prediction on the test example and its relation to other examples

## Problem 2: What is the meaning of “distance awareness”? How do the authors achieve “distance awareness”? Answer this question in two sentences. (15 points)

The meaning of distance awareness is the deep neural network's ability to measure the distance of a given test sample from the collection of training samples with high accuracy. This distance awareness is achieved with the author's usage of "Spectral-normalized Neural Gaussian Process" which adds weight normalization during training and adds a gaussian process to the output layer to achieve this expected level of accuracy in uncertainity measurement.

## Problem 3: Design and implement a toy experiment to showcase the effect of “spectral normalization”. (20 points)
"""

#Import libraries
import matplotlib.pyplot as plt
import sklearn.datasets
import numpy as np